services:
  stats-server:
    build: stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
    volumes:
      - stats-data:/var/lib/postgresql/data

# раскомментировать на втором этапе
#  ewm-service:
#    build: main-service
#    container_name: ewm-service
#    ports:
#      - "8080:8080"
#    environment:
#      - CLIENT_URL=http://stats-server:9090
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
#      - SPRING_DATASOURCE_USERNAME=main
#      - SPRING_DATASOURCE_PASSWORD=main
#    depends_on:
#      - ewm-db
#      - stats-server

#  ewm-db:
#    image: postgres:16.1В
#    container_name: postgres-ewm-main-db
#    environment:
#      - POSTGRES_DB=ewm-main
#      - POSTGRES_USER=main
#      - POSTGRES_PASSWORD=main
#    volumes:
#      - main-data:/var/lib/postgresql/data

volumes:
  stats-data:
#  main-data: